### ISSUE TITLE
rap.port ignored if one port is mapped

### ISSUE THREAD

**Issue by jgrusling** [adi90x/rancher-active-proxy#1]
If one port is mapped from the host to container, then the template will always use that port no matter what. However, rap.port if defined should take priority to determination of what port to utilize.

**Comment by adi90x** [comment]
Hello,
Thanks for reporting this.
It was built like that in order to be able to always have a port, and it
seems to me that exposed port should have priority over anything.
However, I agree with you and will change it to have :
- rap.port
- exposed port
- default port (80)

That default port,  could probably be defined with an environment variable
to make it even more personalizable!

I will try to push that tonight or tomorrow morning !

**Comment by adi90x** [comment]
Just push a branch to change priority order, will merge in few minutes with master !
